window.OERF_LEARNING_RESOURCES = [
  {
    id: "mit-206-fluid-dynamics",
    module: "流体力学",
    priority: "must",
    title: "MIT OCW 2.06 Fluid Dynamics",
    type: "开放课程",
    access: "官方课程页已核验，可在线读或下载课程包",
    landing_url: "https://ocw.mit.edu/courses/2-06-fluid-dynamics-spring-2013/",
    pdf_url: "",
    local_pdf: "",
    why: "物理本科补流体最稳的入口之一，覆盖守恒方程、压力、控制体、黏性流、无量纲分析和边界层直觉。",
    read: "先读 course description、readings 和前几讲；只抽取连续介质、质量/动量守恒、Reynolds number、boundary layer、vorticity 这些服务 BOST 的概念。",
    cache_policy: "公开站只放官方入口；课程整包不塞进 GitHub Pages。"
  },
  {
    id: "mit-225-advanced-fluid",
    module: "流体力学",
    priority: "support",
    title: "MIT OCW 2.25 Advanced Fluid Mechanics",
    type: "开放课程",
    access: "官方课程页已核验",
    landing_url: "https://ocw.mit.edu/courses/2-25-advanced-fluid-mechanics-fall-2013/",
    pdf_url: "",
    local_pdf: "",
    why: "当 2.06 不够时，用它补 vorticity、potential flow、boundary layers 和稳定性等更深内容。",
    read: "不要整门硬啃；只在读到 jet、plume、boundary layer、vorticity 或 turbulence 相关论文时按需查。",
    cache_policy: "公开站只放官方入口。"
  },
  {
    id: "bar-meir-fluid",
    module: "流体力学",
    priority: "support",
    title: "Genick Bar-Meir, Basics of Fluid Mechanics / Potto Project",
    type: "开放教材线索",
    access: "开放教材入口需继续按版本核验",
    landing_url: "https://www.potto.org/fluid-mechanics/",
    pdf_url: "",
    local_pdf: "",
    why: "比正式课本更像速查书，适合补量纲、控制体、Bernoulli、黏性流等基本概念。",
    read: "只作为 MIT OCW 的中文笔记辅助，不用替代主教材。",
    cache_policy: "先放入口，PDF 版本和许可确认后再决定是否本地缓存。"
  },
  {
    id: "white-kundu-batchelor-private",
    module: "流体力学",
    priority: "optional",
    title: "Frank White / Kundu / Batchelor 等经典流体教材",
    type: "商业教材",
    access: "建议图书馆、正版电子书或本地私有库；不上传公开网页",
    landing_url: "",
    pdf_url: "",
    local_pdf: "",
    why: "适合长期补系统流体力学，但不是马上读懂 NeRIF 的最短路径。",
    read: "优先查连续介质、Navier-Stokes、边界层、可压缩流、湍流基础。不要在开题前陷入整本阅读。",
    cache_policy: "若通过学校资源获得电子版，只进入 private_library，不进 GitHub Pages。"
  },
  {
    id: "cefrc-combustion-school",
    module: "燃烧/反应流",
    priority: "must",
    title: "Princeton CEFRC Combustion Summer School Lecture Notes",
    type: "开放讲义集合",
    access: "官方 lecture notes 入口",
    landing_url: "https://cefrc.princeton.edu/combustion-summer-school/lecture-notes",
    pdf_url: "",
    local_pdf: "",
    why: "补燃烧和激光诊断最贴 OERF 的开放材料，覆盖 combustion chemistry、turbulent combustion、laser diagnostics。",
    read: "先读 combustion physics、turbulent premixed flame、laser diagnostics 相关讲义；只理解火焰结构、温度/密度/折射率和非接触诊断需求。",
    cache_policy: "公开站放官方入口；具体 PDF 后续按讲义页逐个缓存或跳转。"
  },
  {
    id: "cefrc-laser-diagnostics-2019",
    module: "燃烧/反应流",
    priority: "support",
    title: "CEFRC 2019 Laser Diagnostics Lecture Notes",
    type: "开放讲义集合",
    access: "官方归档入口",
    landing_url: "https://cefrc.princeton.edu/combustion-summer-school/archived-programs/2019-session/lecture-notes",
    pdf_url: "",
    local_pdf: "",
    why: "用于补 PLIF、PIV、LII、吸收光谱等 OERF 光学诊断语境。",
    read: "只抽取诊断物理、误差来源和实验链路。不要先深挖燃烧机理。",
    cache_policy: "公开站放官方入口；后续可按需缓存单篇开放 PDF。"
  },
  {
    id: "turns-law-private",
    module: "燃烧/反应流",
    priority: "optional",
    title: "Turns, An Introduction to Combustion / Law, Combustion Physics",
    type: "商业教材",
    access: "建议图书馆、正版电子书或本地私有库；不上传公开网页",
    landing_url: "",
    pdf_url: "",
    local_pdf: "",
    why: "两本是燃烧基础经典；如果后续真实题目涉及 turbulent premixed flames 或 NH3/CH4，可按章节补。",
    read: "只读火焰类型、绝热火焰温度、预混/扩散火焰、火焰速度、湍流燃烧概念。",
    cache_policy: "订阅/图书馆 PDF 只进 private_library。"
  },
  {
    id: "mit-271-optics",
    module: "光学/诊断",
    priority: "must",
    title: "MIT OCW 2.71 Optics",
    type: "开放课程",
    access: "官方课程页已核验",
    landing_url: "https://ocw.mit.edu/courses/2-71-optics-spring-2009/",
    pdf_url: "",
    local_pdf: "",
    why: "补几何光学、成像、傅里叶光学和光学系统直觉，为 BOS/BOST 的相机、背景、光线偏折打底。",
    read: "优先读 geometrical optics、imaging、aberration、Fourier optics 的讲义/幻灯。不要一开始深挖量子光学。",
    cache_policy: "公开站放官方入口。"
  },
  {
    id: "cakir-bos-thesis",
    module: "光学/诊断",
    priority: "support",
    title: "Bora Cakir, Optical Diagnostics with Background Oriented Schlieren: A Practical Guide",
    type: "开放博士论文",
    access: "Lund Research Portal 官方页面和 PDF 直链",
    landing_url: "https://portal.research.lu.se/en/publications/optical-diagnostics-with-background-oriented-schlieren-a-practica/",
    pdf_url: "https://lucris.lub.lu.se/ws/portalfiles/portal/195450596/e-nailing_ex_Bora.pdf",
    local_pdf: "",
    why: "非常适合初学者补 BOS 实验直觉：背景图案、光流位移、Bunsen flame、laminar burning velocity、swirl flame 案例。",
    read: "先看目录、实验搭建、background pattern、optical-flow processing 和 flame case study。",
    cache_policy: "PDF 较大，公开站先放官方直链；本地可按需下载到学习库。"
  },
  {
    id: "settles-private",
    module: "光学/诊断",
    priority: "optional",
    title: "Settles, Schlieren and Shadowgraph Techniques",
    type: "商业教材",
    access: "建议图书馆、正版电子书或本地私有库；不上传公开网页",
    landing_url: "",
    pdf_url: "",
    local_pdf: "",
    why: "经典纹影/阴影技术书，适合理解 schlieren、shadowgraph、BOS 的历史和实验差异。",
    read: "只查 schlieren sensitivity、shadowgraph vs schlieren、large-field/focusing schlieren 和 BOS 背景章节。",
    cache_policy: "若通过 VPN 获得，只进入 private_library 或本地教材私有区。"
  },
  {
    id: "kak-slaney-pct",
    module: "反问题/层析",
    priority: "must",
    title: "Kak & Slaney, Principles of Computerized Tomographic Imaging",
    type: "开放教材章节",
    access: "Slaney 官方目录页已核验，章节 PDF 由 Purdue 页面提供",
    landing_url: "https://www.slaney.org/pct/pct-toc.html",
    pdf_url: "https://engineering.purdue.edu/~malcolm/pct/CTI_Ch03.pdf",
    local_pdf: "",
    why: "层析反问题经典入门。BOST/NeRIF 的 projection、Radon、FBP、ART/SART、病态性都能在这里找到根。",
    read: "先看目录、projection/Radon、FBP、ART/SART 和 limited-angle 相关章节；不用整本细读。",
    cache_policy: "公开站放官方章节入口；不重新打包整本书。"
  },
  {
    id: "scikit-image-radon",
    module: "反问题/层析",
    priority: "must",
    title: "scikit-image Radon Transform Example",
    type: "官方代码教程",
    access: "官方文档入口",
    landing_url: "https://scikit-image.org/docs/stable/auto_examples/transform/plot_radon_transform.html",
    pdf_url: "",
    local_pdf: "",
    why: "最适合把 CT/层析从公式变成代码。能快速生成 phantom、sinogram、FBP/SART 和误差图。",
    read: "直接跑示例，改视角数、噪声和迭代次数，作为 BOST toy 的反问题前置训练。",
    cache_policy: "文档在线更新，公开站只放入口。"
  },
  {
    id: "hansen-discrete-inverse-private",
    module: "反问题/层析",
    priority: "optional",
    title: "Hansen, Discrete Inverse Problems 等反问题教材",
    type: "商业/受控教材",
    access: "建议图书馆、正版电子书或本地私有库；不上传公开网页",
    landing_url: "",
    pdf_url: "",
    local_pdf: "",
    why: "如果你要把正则化、半收敛、L-curve、Tikhonov 写得更扎实，可以作为进阶参考。",
    read: "只查 ill-posedness、Tikhonov、iterative regularization、noise amplification。",
    cache_policy: "订阅/图书馆 PDF 只进 private_library。"
  },
  {
    id: "szeliski-cv",
    module: "计算机视觉/图像",
    priority: "support",
    title: "Richard Szeliski, Computer Vision: Algorithms and Applications",
    type: "作者开放教材页",
    access: "作者官方页面已核验，下载页在线表单/入口由作者维护",
    landing_url: "https://szeliski.org/Book/",
    pdf_url: "https://szeliski.org/Book/download.php",
    local_pdf: "",
    why: "用于补相机模型、光流、特征、图像配准和 3D 视觉直觉。",
    read: "优先查 image formation、motion/optical flow、feature matching、camera calibration、multi-view geometry。",
    cache_policy: "公开站放作者入口；不绕过作者下载机制。"
  },
  {
    id: "openpiv-docs",
    module: "PIV/速度场",
    priority: "must",
    title: "OpenPIV Documentation",
    type: "开源项目文档",
    access: "官方文档入口",
    landing_url: "https://openpiv.readthedocs.io/en/latest/",
    pdf_url: "",
    local_pdf: "",
    why: "PIV-BOST 入门必须先懂 PIV 图像对、互相关窗口、subpixel peak 和速度换算。",
    read: "跑一个 synthetic particle image pair，理解 interrogation window、overlap、validation、scaling。",
    cache_policy: "文档在线更新，公开站只放入口。"
  },
  {
    id: "pytorch-basics",
    module: "PyTorch/科学计算",
    priority: "must",
    title: "PyTorch Learn the Basics",
    type: "官方教程",
    access: "官方教程入口已核验",
    landing_url: "https://pytorch.org/tutorials/beginner/basics/intro.html",
    pdf_url: "",
    local_pdf: "",
    why: "NeRIF/NeDF/NRIP 的最小实现离不开 tensor、autograd、optimizer、dataset 和 loss。",
    read: "只读 tensor、autograd、optimization、save/load；立刻写坐标 MLP 拟合三维 phantom。",
    cache_policy: "文档在线更新，公开站只放入口。"
  },
  {
    id: "d2l",
    module: "PyTorch/科学计算",
    priority: "support",
    title: "Dive into Deep Learning",
    type: "开放教材",
    access: "官方在线书已核验",
    landing_url: "https://d2l.ai/",
    pdf_url: "",
    local_pdf: "",
    why: "用于补神经网络训练、优化、正则化和 PyTorch 代码风格。",
    read: "只读线性层、MLP、优化、正则化、卷积基础；不必把整本深度学习书刷完。",
    cache_policy: "公开站放官方入口。"
  },
  {
    id: "deep-learning-book",
    module: "PyTorch/科学计算",
    priority: "optional",
    title: "Goodfellow, Bengio & Courville, Deep Learning",
    type: "开放在线书",
    access: "官方在线书已核验",
    landing_url: "https://www.deeplearningbook.org/",
    pdf_url: "",
    local_pdf: "",
    why: "用于补优化、正则化、表示学习和泛化，不是第一月必读。",
    read: "按需查 chapter 6 MLP、chapter 7 regularization、chapter 8 optimization。",
    cache_policy: "公开站放官方入口。"
  },
  {
    id: "scipy-lectures",
    module: "PyTorch/科学计算",
    priority: "support",
    title: "Scientific Python Lectures",
    type: "开放讲义",
    access: "官方在线讲义入口",
    landing_url: "https://scipy-lectures.org/",
    pdf_url: "",
    local_pdf: "",
    why: "补 NumPy、SciPy、Matplotlib、image processing 和 optimization，比直接读大型文档更省力。",
    read: "优先查 NumPy array、Matplotlib plotting、SciPy optimization、image processing。",
    cache_policy: "公开站放官方入口。"
  },
  {
    id: "mit-1806sc-linear-algebra",
    module: "数学/线性代数",
    priority: "must",
    title: "MIT OCW 18.06SC Linear Algebra",
    type: "开放课程",
    access: "MIT OCW 官方课程页已核验",
    landing_url: "https://ocw.mit.edu/courses/18-06sc-linear-algebra-fall-2011/",
    pdf_url: "",
    local_pdf: "",
    why: "补齐列空间、正交投影、最小二乘、特征值和 SVD，才能真正理解少视角反演里的可观测与零空间。",
    read: "优先学 column/null space、orthogonality、least squares、eigenvalues、SVD；每节都用一个小矩阵写 NumPy 验证。",
    cache_policy: "公开站只放官方入口；课程包不重新打包上传。"
  },
  {
    id: "pytorch-autograd",
    module: "PyTorch/科学计算",
    priority: "must",
    title: "PyTorch Automatic Differentiation Tutorial",
    type: "官方代码教程",
    access: "PyTorch 官方教程已核验",
    landing_url: "https://docs.pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html",
    pdf_url: "",
    local_pdf: "",
    why: "NeRIF 的坐标梯度、forward loss 和神经算子训练都依赖 autograd；这是从公式到可运行梯度检查的最短入口。",
    read: "跑通 requires_grad、backward、detach 和 no_grad，再对一个二次函数做有限差分梯度核对。",
    cache_policy: "在线文档持续更新，公开站只放官方入口。"
  },
  {
    id: "neuraloperator-intro",
    module: "算子学习",
    priority: "must",
    title: "Neural Operators: an Introduction",
    type: "官方理论导读",
    access: "NeuralOperator 2.0 官方文档已核验",
    landing_url: "https://neuraloperator.github.io/dev/theory_guide/neural_operators.html",
    pdf_url: "",
    local_pdf: "",
    why: "先把函数到函数的映射、离散化和普通网络的区别讲清楚，避免把 neural field、PINN 和 operator learning 混为一谈。",
    read: "只抽取 operator map、discretization 和 approximation 三个定义，并用 BOST 输入/输出变量重写。",
    cache_policy: "在线文档持续更新，公开站只放官方入口。"
  },
  {
    id: "neuraloperator-fno",
    module: "算子学习",
    priority: "must",
    title: "Fourier Neural Operator Theory Guide",
    type: "官方理论导读",
    access: "NeuralOperator 2.0 官方文档已核验",
    landing_url: "https://neuraloperator.github.io/dev/theory_guide/fno.html",
    pdf_url: "",
    local_pdf: "",
    why: "解释 spectral convolution、mode truncation、lifting/projection 和分辨率测试，是读 FNO 代码前的最小理论层。",
    read: "自己写一个 1D spectral layer，打印实 FFT 张量形状并扫描 modes。",
    cache_policy: "在线文档持续更新，公开站只放官方入口。"
  },
  {
    id: "neuraloperator-darcy",
    module: "算子学习",
    priority: "must",
    title: "NeuralOperator Darcy FNO Tutorial",
    type: "官方可运行教程",
    access: "NeuralOperator 官方 example 已核验",
    landing_url: "https://neuraloperator.github.io/dev/auto_examples/models/plot_FNO_darcy.html",
    pdf_url: "",
    local_pdf: "",
    why: "提供 data processor、FNO、Lp/H1 loss、trainer 和 resolution test 的完整最小闭环。",
    read: "先在 CPU 或小 GPU 跑通，再只改数据尺寸、modes 和 width，保存训练曲线及分辨率迁移表。",
    cache_policy: "代码随官方库更新，公开站只放入口。"
  },
  {
    id: "fno-paper",
    module: "算子学习",
    priority: "must",
    title: "Fourier Neural Operator for Parametric PDEs",
    type: "核心论文",
    access: "ICLR 2021 官方页面已核验",
    landing_url: "https://iclr.cc/virtual/2021/poster/3281",
    pdf_url: "",
    local_pdf: "",
    why: "FNO 根论文，必须提取它真正证明的任务、训练分布、分辨率实验和计算预算，不能把结论直接搬到 BOST。",
    read: "精读 spectral kernel 公式、Navier-Stokes 数据、baseline 和 zero-shot resolution 实验；另列不可迁移项。",
    cache_policy: "公开站放官方会议入口和本站论文导读。"
  },
  {
    id: "deeponet-paper",
    module: "算子学习",
    priority: "must",
    title: "Learning Nonlinear Operators via DeepONet",
    type: "核心论文",
    access: "Nature Machine Intelligence 官方页已核验",
    landing_url: "https://www.nature.com/articles/s42256-021-00302-5",
    pdf_url: "",
    local_pdf: "",
    why: "branch/trunk 结构非常适合解释“多相机观测函数到任意三维坐标查询”的接口。",
    read: "画出 branch sensors、trunk query coordinates 和输出场的张量图，再判断固定/可变相机布局的限制。",
    cache_policy: "订阅全文不公开缓存；保留出版社入口和合法开放版本线索。"
  },
  {
    id: "deepxde-operator",
    module: "算子学习",
    priority: "support",
    title: "DeepXDE Operator-Learning Demos",
    type: "官方可运行教程",
    access: "DeepXDE 官方文档已核验",
    landing_url: "https://deepxde.readthedocs.io/en/latest/demos/operator.html",
    pdf_url: "",
    local_pdf: "",
    why: "用很小的 antiderivative/Poisson 任务理解 DeepONet 的 aligned、unaligned 和 physics-informed 数据接口。",
    read: "只跑一个 aligned 和一个 unaligned 示例，记录 branch/trunk/output shape 与 loss。",
    cache_policy: "在线文档持续更新，公开站只放入口。"
  },
  {
    id: "nerif-paper",
    module: "BOST/NeRIF 论文",
    priority: "must",
    title: "Neural Refractive Index Field",
    type: "何远哲主线论文",
    access: "arXiv 作者公开版与 Physics of Fluids 正式页已核验",
    landing_url: "https://arxiv.org/abs/2409.14722",
    pdf_url: "https://arxiv.org/pdf/2409.14722",
    local_pdf: "../paper_library/paper_detail.html?id=nerif-he-2025",
    why: "定义本项目真正要尊重的 BOST forward、折射率场、采样、loss 和实验边界；它是物理底盘，不是算子架构来源。",
    read: "做公式-代码-图表三列笔记，明确观测量、未知量、ray model、训练/优化对象和评价指标。",
    cache_policy: "公开缓存仅使用 arXiv 作者版；出版社版本不重复上传。"
  },
  {
    id: "deep-null-space",
    module: "反问题/层析",
    priority: "support",
    title: "Deep Null Space Learning for Inverse Problems",
    type: "方法论文",
    access: "Inverse Problems DOI 与 arXiv 作者版已核验",
    landing_url: "https://arxiv.org/abs/1806.06137",
    pdf_url: "https://arxiv.org/pdf/1806.06137",
    local_pdf: "../paper_library/paper_detail.html?id=deep-null-space-learning-schwab-2019",
    why: "给出用 Id-A+ A 投影保持数据一致性的严格邻近方法，但其线性设定和结论不能直接迁移到 BOST。",
    read: "只抽取投影形式、假设、收敛结论和适用边界，再在小矩阵上验证 support leakage。",
    cache_policy: "可使用作者公开版；本站导读明确跨模态边界。"
  },
  {
    id: "neural-correction",
    module: "算子学习",
    priority: "support",
    title: "Neural Correction Operator",
    type: "方法论文",
    access: "JCP 2026 DOI 与 arXiv 作者版已核验",
    landing_url: "https://arxiv.org/abs/2507.18875",
    pdf_url: "https://arxiv.org/pdf/2507.18875",
    local_pdf: "../paper_library/paper_detail.html?id=neural-correction-operator-bhat-2026",
    why: "为“有限步传统重建 + learned correction”提供最近先例，适合设计同预算 direct/correction 对照。",
    read: "列出 EIT 与 BOST 在 forward、粗解误差、观测预算和数据一致性上的相同与不同。",
    cache_policy: "可使用作者公开版；不把 EIT 百分比当作 BOST 证据。"
  },
  {
    id: "open-bos-dataset",
    module: "BOST/NeRIF 论文",
    priority: "must",
    title: "Open-Source BOS Tomography Dataset of High-Speed Flow",
    type: "开放数据与论文",
    access: "Experiments in Fluids 2026 官方页已核验",
    landing_url: "https://link.springer.com/article/10.1007/s00348-026-04189-z",
    pdf_url: "",
    local_pdf: "../paper_library/paper_detail.html?id=open-bos-dataset-molnar-2026",
    why: "把 toy 转向公开真实 BOS 的关键入口，可先做数据健康、标定和传统基线，不必立刻训练大模型。",
    read: "核对许可、相机布局、标定、文件结构、参考量与推荐 split，先形成数据卡。",
    cache_policy: "论文和数据分别遵守官方许可；公开站不重新分发未经确认的大数据包。"
  },
  {
    id: "paper-library-core",
    module: "BOST/NeRIF 论文",
    priority: "must",
    title: "OERF / BOST Paper Library",
    type: "本项目论文库",
    access: "本地与公开网页均可访问；只缓存开放 PDF",
    landing_url: "../paper_library/index.html",
    pdf_url: "",
    local_pdf: "",
    why: "补课最终都要回到论文。先读 NeRIF、PIV-BOST、4D BOST，再读 NeDF/NRIP、UBOST、BOS 综述和公开数据论文。",
    read: "用术语标签辅助阅读；每篇精读只提取公式链条、观测量、未知量、baseline、指标和可复现数据。",
    cache_policy: "开放 PDF 可缓存；VPN/订阅 PDF 只进 private_library。"
  }
];
